###############################################################################
#
# Abstract:
#   Collect linux kernel build parameters
#
# Revision History:
#   27/05/2023 - Maxim Lyadvinsky - Created
#
###############################################################################

# Generated cmake file
cmake_generated_dir=../cmake/generated
kbuild_cmake=$cmake_generated_dir/kbuild.cmake
kbuild_cmake_tmp=${kbuild_cmake}.tmp
inc_generated_dir=../../inc/kernel/linux/generated
precompiler_h=$inc_generated_dir/precompiler.h

# Setting up output beautifier
bold=$(tput bold)
red=$(tput setaf 1)
normal=$(tput sgr0)

# Kbuild cleanup
cleanup='rm -rf *.o *~ core .depend .*.cmd *.ko *.mod *.mod.c .tmp_versions *.order *.symvers'


###############################################################################
#
# Sed scripts
#
###############################################################################

# Sed script for parsing compiler parameters
sed_compiler_options='
    s/^\(.*\)-Wp,[^ ]*\( .*\)$/\1\2/;
    s/^[^:]*:= *\([^ ]\+\) [^-]*\(-.*\) -o.*$/#  Autogenerated file with detected compiler and linker for kernel module\
    # Compiler \1\
    target_compile_options(${PROJECT_NAME} PRIVATE $<$<COMPILE_LANGUAGE:C>:\2>)\
    target_compile_options(${PROJECT_NAME} PRIVATE $<$<COMPILE_LANGUAGE:CXX>:\2>)/;
    /^#  Autogenerated/ {
        s/-I./-I${KERNEL_HEADERS}/g;
        s/ -/\n        -/g;
        s/>:-/>:\n        -/g;
        p;
    }';

# Sed script for parsing linker parameters
sed_linker_options='
    s/^[^:]*:= *\([^ ].\) [^-]*\(-.*\) -o.*$/\
        # Linker \1\
        target_link_options(${PROJECT_NAME} PRIVATE \2)/p;';

# Sed script for moving -include options to kernel/linux/_kernel.h header to work around cmake' options de-dup feature
sed_kernel_h='s/^.*-include.*\(linux.*\)$/#include <\1>/p';
sed_remove_includes='/^.*-include.*$/! p';



###############################################################################
#
# Process kbuild stub
#
###############################################################################

echo $bold'VSYS: Building empty Linux kernel module'$normal
make
make_exit=$?
if [ "$make_exit" != "0" ] ; then
    echo ${bold}${red}VSYS: Error $make_exit building kbuild stub${normal}
    exit $make_exit
fi

echo $bold'VSYS: Detecting compiler parameters'$normal
mkdir -p $cmake_generated_dir
sed -n -e "$sed_compiler_options" <.kbuild.o.cmd >$kbuild_cmake_tmp
mkdir -p $inc_generated_dir
echo '//  Autogenerated header with detected precompiler includes' >$precompiler_h
sed -n -e "$sed_kernel_h" <$kbuild_cmake_tmp >>$precompiler_h
sed -n -e "$sed_remove_includes" <$kbuild_cmake_tmp >$kbuild_cmake
rm $kbuild_cmake_tmp

echo $bold'VSYS: Detecting linker parameters'$normal
sed -n -e "$sed_linker_options" <.kbuild.ko.cmd >>$kbuild_cmake

echo $bold'VSYS: Cleaning up'$normal
$cleanup
